In [11]:
import numpy as np
data = np.array([[1, 2, 5.2, -1.2]]).reshape(1, -1)

data




array([[ 1. ,  2. ,  5.2, -1.2]])

In [2]:
! export METAFLOW_PROFILE=oleg2

In [3]:
! python RF-deploy-MVP.py run

Metaflow 2.5.0 executing ClassificationFlow for user:hba
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2022-03-25 16:25:48.920 Workflow starting (run-id 1648185948917580):
2022-03-25 16:25:48.928 [1648185948917580/start/1 (pid 2882)] Task is starting.
2022-03-25 16:25:50.978 [1648185948917580/start/1 (pid 2882)] Task finished successfully.
2022-03-25 16:25:50.987 [1648185948917580/rf_model/2 (pid 2890)] Task is starting.
2022-03-25 16:25:52.135 [1648185948917580/rf_model/2 (pid 2890)] Task finished successfully.
2022-03-25 16:25:52.144 [1648185948917580/train/3 (pid 2895)] Task is starting.
2022-03-25 16:25:53.205 [1648185948917580/train/3 (pid 2895)] Task finished successfully.
2022-03-25 16:25:53.214 [1648185948917580/deploy/4 (pid 2900)] Task is starting.
2022-03-25 16:25:54.395 [1648185948917580/deploy/4 (pid 2900)] <flow ClassificationFlow step deploy> failed:
2022-03-25 16:25:54.400 [1648185948917580/deploy/4 (pid 2900)] Internal error
2

In [32]:
X[1:3]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [7]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris['data']

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
X[1:4]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [10]:
import boto3
import pandas as pd

# Create a low-level client representing Amazon SageMaker Runtime
sagemaker_runtime = boto3.client("sagemaker-runtime", region_name='us-west-2')

# The name of the endpoint. The name must be unique within an AWS Region in your AWS account. 

endpoint_name='HBA-RF-endpoint-1648215885857'


# csv serialization
response = sagemaker_runtime.invoke_endpoint(
    EndpointName=endpoint_name,
    Body=pd.DataFrame(X).to_csv(header=False, index=False),
    ContentType="text/csv",
)

print(response["Body"].read())

b'[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]'


In [3]:
t = pd.DataFrame(X[1:10]).to_csv(header=False, index=False)

In [4]:
t

'4.9,3.0,1.4,0.2\n4.7,3.2,1.3,0.2\n4.6,3.1,1.5,0.2\n5.0,3.6,1.4,0.2\n5.4,3.9,1.7,0.4\n4.6,3.4,1.4,0.3\n5.0,3.4,1.5,0.2\n4.4,2.9,1.4,0.2\n4.9,3.1,1.5,0.1\n'

In [23]:
import numpy as np
samples = []
for r in t.split():
    print(r)
    samples.append(list(map(float,r.split(','))))
np.array(samples)

4.9,3.0,1.4,0.2
4.7,3.2,1.3,0.2
4.6,3.1,1.5,0.2
5.0,3.6,1.4,0.2
5.4,3.9,1.7,0.4
4.6,3.4,1.4,0.3
5.0,3.4,1.5,0.2
4.4,2.9,1.4,0.2
4.9,3.1,1.5,0.1


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
! aws-vault login devsandbox

In [7]:
import numpy as np
data = np.random.random(1000)
data = [[d] for d in data]

In [9]:
# https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints-test-endpoints.html
# https://docs.aws.amazon.com/cli/latest/reference/sagemaker-runtime/invoke-endpoint.html
# https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-inference.html#ir-serialization

import boto3

# Create a low-level client representing Amazon SageMaker Runtime
sagemaker_runtime = boto3.client("sagemaker-runtime", region_name='us-west-2')

# The name of the endpoint. The name must be unique within an AWS Region in your AWS account. 
#endpoint_name='RF-endpoint-1648025507362'
endpoint_name='RF-endpoint-1648169001436'
# endpoint_name='regression-1646368875724-endpoint'
endpoint_name='RF-endpoint-1648171008125'

# After you deploy a model into production using SageMaker hosting 
# services, your client applications use this API to get inferences 
# from the model hosted at the specified endpoint.
response = sagemaker_runtime.invoke_endpoint(
                            EndpointName=endpoint_name, 
                            #Body=f"{data}",
                            #Body=bytes(r'{"instances":' + f"{data}" + '}', 'utf-8'), # Replace with your own data
                            Body=bytes(f"{data}", 'utf-8'), 
                            #ContentType='application/json',
                            )

# Optional - Print the response body and decode it so it is human read-able.
print(response['Body'].read().decode('utf-8'))

ValidationError: An error occurred (ValidationError) when calling the InvokeEndpoint operation: Endpoint RF-endpoint-1648171008125 of account 006988687827 not found.

In [12]:
import boto3
import pandas as pd

# Create a low-level client representing Amazon SageMaker Runtime
sagemaker_runtime = boto3.client("sagemaker-runtime", region_name='us-west-2')

# The name of the endpoint. The name must be unique within an AWS Region in your AWS account. 
#endpoint_name='RF-endpoint-1648025507362'
endpoint_name='RF-endpoint-1648169001436'
# endpoint_name='regression-1646368875724-endpoint'
endpoint_name='RF-endpoint-1648171008125'


# csv serialization
response = sagemaker_runtime.invoke_endpoint(
    EndpointName=endpoint_name,
    Body=pd.DataFrame(data).to_csv(header=False, index=False).encode("utf-8"),
    ContentType="text/csv",
)

print(response["Body"].read())

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/RF-endpoint-1648171008125 in account 006988687827 for more information.

In [33]:
bytes(f"{data}", 'utf-8')

b'[[ 1. ]\n [ 2. ]\n [ 5.2]\n [-1.2]]'

In [13]:
'{"instances":' + f"{data}" + '}', 'utf-8'

('{"instances":[[ 1. ]\n [ 2. ]\n [ 5.2]\n [-1.2]]}', 'utf-8')

In [17]:
bytes(r'{"instances":' + f"{data}" + '}', 'utf-8')

b'{"instances":[[ 1. ]\n [ 2. ]\n [ 5.2]\n [-1.2]]}'

In [ ]:
import ipywidgets as widgets

In [ ]:
widgets.BoundedFloatText(
    value=7.5,
    min=0,
    max=10.0,
    step=0.1,
    description='Text:',
    disabled=False
)

## boat

In [ ]:
test_inp = {'instances': [[10,124,12,45,43]+[0]*15],
                'mask' : token_mapping['token2id'].get('mask', None)}

In [ ]:
data = [[10,124,12,45,43]+[0]*15]

In [ ]:
# https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints-test-endpoints.html
# https://docs.aws.amazon.com/cli/latest/reference/sagemaker-runtime/invoke-endpoint.html
# https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-inference.html#ir-serialization

import boto3

# Create a low-level client representing Amazon SageMaker Runtime
sagemaker_runtime = boto3.client("sagemaker-runtime", region_name='us-west-2')

# The name of the endpoint. The name must be unique within an AWS Region in your AWS account. 
endpoint_name='recommendation-1646891533365-endpoint'
# endpoint_name='regression-1646368875724-endpoint'

# After you deploy a model into production using SageMaker hosting 
# services, your client applications use this API to get inferences 
# from the model hosted at the specified endpoint.
response = sagemaker_runtime.invoke_endpoint(
                            EndpointName=endpoint_name, 
                            Body=bytes('{"instances":' + f"{data}" + '}', 'utf-8'), # Replace with your own data
                            ContentType='application/json',
                            )

# Optional - Print the response body and decode it so it is human read-able.
print(response['Body'].read().decode('utf-8'))